import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{  //this is a typescript.
  children: React.ReactNode; //React type for the children prop, which can be any valid React node (elements, strings, numbers, etc.).
}>) {
  return (
    <html
      lang="en">
      <body className="min-h-full flex flex-col">
      <Navbar/>
        {children}</body>
    </html>
  );
}
